FROM prefecthq/prefect:3.7.8.dev3-python3.12-conda

# 修复 _distutils_hack 错误（关键步骤）
RUN rm -f /opt/conda/envs/prefect/lib/python3.12/site-packages/distutils-precedence.pth

# pip换国内清华的源
RUN conda run -n prefect pip install -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple --upgrade pip \
&& conda run -n prefect pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple

# 安装项目依赖库
WORKDIR /code/
COPY ./requirements.txt .
RUN conda run -n prefect pip install --no-cache-dir -r requirements.txt

# 启动项目
WORKDIR /code/app/
