# https://github.com/vectorize-io/hindsight/blob/main/docker/docker-compose/custom-models/docker-compose.yaml
services:
  hermes:
    # 使用官方镜像
    image: nousresearch/hermes-agent:v2026.6.19
    container_name: hermes
    restart: unless-stopped
    # 环境变量配置
    environment:
      - TZ=Asia/Shanghai
      # 启用 Web Dashboard
      - HERMES_DASHBOARD=1
      - HERMES_DASHBOARD_HOST=0.0.0.0
      - HERMES_DASHBOARD_INSECURE=1
      # 启用 API Server
      - API_SERVER_ENABLED=true
      - API_SERVER_HOST=0.0.0.0
      # 【重要】修改下面这个 API Key，使用强密码
      - API_SERVER_KEY=${HERMES_API_KEY}
      # 设置容器内的工作目录，要与 volumes 挂载路径一致
      - HERMES_HOME=/opt/data/.hermes
      # LLM
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DEEPSEEK_BASE_URL=https://api.deepseek.com
    # 关键：持久化存储的挂载点
    volumes:
      # Hermes 的核心数据（配置、记忆、会话、技能）会存到这里
      - hermes_data:/opt/data/
      # 可选：映射日志目录，方便查看
      - hermes_logs:/app/logs/
    # 可选：暴露 Web 管理界面和 API
    ports:
      - "8642:8642" # API 服务端口
      - "9119:9119" # Web Dashboard 端口
    command: ['gateway', 'run']

    # 资源限制建议
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "2.0"
  
  hindsight:
    build:
      context: .
      dockerfile: dockerfile
    container_name: hindsight
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - HF_ENDPOINT=https://hf-mirror.com    #使用hugging face国内镜像
      - HINDSIGHT_API_LLM_PROVIDER=deepseek
      - HINDSIGHT_API_LLM_API_KEY=${DEEPSEEK_API_KEY}
      - HINDSIGHT_API_LLM_MODEL=deepseek-v4-flash 
      - HINDSIGHT_API_LLM_BASE_URL=https://api.deepseek.com 
      - HINDSIGHT_API_EMBEDDINGS_PROVIDER=local
      - HINDSIGHT_API_EMBEDDINGS_LOCAL_MODEL=sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
      - HINDSIGHT_API_RERANKER_PROVIDER=local
      - HINDSIGHT_API_RERANKER_LOCAL_MODEL=cross-encoder/mmarco-mMiniLMv2-L12-H384-v1
      - HINDSIGHT_CONTROL_PLANE_ENABLED=true # 启用 WebUI
      - HF_HUB_OFFLINE=1
      - TRANSFORMERS_OFFLINE=1
    volumes:
      - hindsight_data:/home/hindsight/.pg0
    ports:
      - "8888:8888" # API Server
      - "9999:9999" # Web UI

volumes:
  hermes_data:
    name: hermes_data
  hermes_logs:
    name: hermes_logs
  hindsight_data:
    name: hindsight_data
